[package]
name = "letsconnectdreams"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.3.6", features = ["postgres", "network-address", "numeric"] }
dotenvy = { version = "0.15" }
ipnetwork = "0.21.1"
